name: 'Push NuGet Package'
description: 'Composite action to build and push a NuGet package for a .NET project.'

inputs:
  project-path:
    description: 'Path to the .csproj file or project directory'
    required: true
  nuget-api-key:
    description: 'NuGet API key for authentication'
    required: true
  nuget-source:
    description: 'NuGet source URL (default: https://api.nuget.org/v3/index.json)'
    required: false
    default: 'https://api.nuget.org/v3/index.json'
  dotnet-version:
    description: 'Version of .NET to use'
    required: false
    default: '9.0.x'
  configuration:
    description: 'Build configuration (default: Release)'
    required: false
    default: 'Release'
  skip-duplicate:
    description: 'Skip pushing if package version already exists'
    required: false
    default: 'true'
  include-symbols:
    description: 'Include symbol packages'
    required: false
    default: 'true'

outputs:
  package-path:
    description: 'Path to the generated package file'
    value: ${{ steps.build.outputs.package-path }}

runs:
  using: "composite"
  steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Check .NET installation
      id: check_dotnet
      run: |
        REQUIRED_VERSION="${{ inputs.dotnet-version }}"
        echo "Required .NET version: $REQUIRED_VERSION"
        
        if command -v dotnet >/dev/null 2>&1 && dotnet --version >/dev/null 2>&1; then
          CURRENT_VERSION=$(dotnet --version)
          echo "Current .NET version: $CURRENT_VERSION"
          
          # Check if the required version matches (handle x patterns like 9.0.x)
          if [[ "$REQUIRED_VERSION" == *".x" ]]; then
            VERSION_PATTERN="${REQUIRED_VERSION%.x}"
            if [[ "$CURRENT_VERSION" == "$VERSION_PATTERN"* ]]; then
              echo ".NET version matches requirement ($CURRENT_VERSION)"
              echo "skip_setup=true" >> $GITHUB_OUTPUT
            else
              echo "Version mismatch. Need: $REQUIRED_VERSION, Have: $CURRENT_VERSION"
              echo "skip_setup=false" >> $GITHUB_OUTPUT
            fi
          elif [[ "$CURRENT_VERSION" == "$REQUIRED_VERSION" ]]; then
            echo "Exact .NET version match ($CURRENT_VERSION)"
            echo "skip_setup=true" >> $GITHUB_OUTPUT
          else
            echo "Version mismatch. Need: $REQUIRED_VERSION, Have: $CURRENT_VERSION"
            echo "skip_setup=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "⚠️ .NET not found, will install"
          echo "skip_setup=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Setup .NET
      if: steps.check_dotnet.outputs.skip_setup != 'true'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
      
    - name: Restore dependencies
      run: dotnet restore ${{ inputs.project-path }}
      shell: bash

    - name: Build and pack
      id: build
      run: |
        # Build and create NuGet package
        dotnet pack ${{ inputs.project-path }} \
          --configuration ${{ inputs.configuration }} \
          --no-restore \
          --output ./packages \
          $([ "${{ inputs.include-symbols }}" = "true" ] && echo "--include-symbols --include-source")
        
        # Find the generated package
        PACKAGE_PATH=$(find ./packages -name "*.nupkg" ! -name "*.symbols.nupkg" | head -1)
        echo "package-path=$PACKAGE_PATH" >> $GITHUB_OUTPUT
        echo "Package created: $PACKAGE_PATH"
        
        # List all generated packages
        echo "Generated packages:"
        ls -la ./packages/
      shell: bash

    - name: Push to NuGet
      run: |
        PACKAGE_PATH="${{ steps.build.outputs.package-path }}"
        
        if [ ! -f "$PACKAGE_PATH" ]; then
          echo "Error: Package file not found at $PACKAGE_PATH"
          exit 1
        fi
        
        echo "Pushing package: $PACKAGE_PATH"
        
        # Push the package
        dotnet nuget push "$PACKAGE_PATH" \
          --source ${{ inputs.nuget-source }} \
          --api-key ${{ inputs.nuget-api-key }} \
          $([ "${{ inputs.skip-duplicate }}" = "true" ] && echo "--skip-duplicate")
        
        # Push symbols package if it exists and include-symbols is true
        if [ "${{ inputs.include-symbols }}" = "true" ]; then
          SYMBOLS_PACKAGE=$(echo "$PACKAGE_PATH" | sed 's/\.nupkg$/.symbols.nupkg/')
          if [ -f "$SYMBOLS_PACKAGE" ]; then
            echo "Pushing symbols package: $SYMBOLS_PACKAGE"
            dotnet nuget push "$SYMBOLS_PACKAGE" \
              --source ${{ inputs.nuget-source }} \
              --api-key ${{ inputs.nuget-api-key }} \
              $([ "${{ inputs.skip-duplicate }}" = "true" ] && echo "--skip-duplicate")
          fi
        fi
        
        echo "Package push completed successfully!"
      shell: bash